'            FreeBasic header file, auto-generated by
'                       ### girtobac ###
' LGPLv2.1 (C) 2013-2022 by Thomas{ doT ]Freiherr[ At ]gmx[ DoT }net
' Auto-translated from file ../../gir_headers/input/JSCore-3.0.gir
#INCLUDE ONCE "_GirToBac-0.0.bi"
' Repository version 1.2
TYPE AS _JSGlobalContextRef JSGlobalContextRef
TYPE AS _JSValueRef JSValueRef
EXTERN "C"
' P_X

' P_3

' P_4

END EXTERN

