'            FreeBasic header file, auto-generated by
'                       ### girtobac ###
' LGPLv2.1 (C) 2013-2022 by Thomas{ doT ]Freiherr[ At ]gmx[ DoT }net
' Auto-translated from file /usr/share/gir-1.0/win32-1.0.gir
#INCLUDE ONCE "_GirToBac-0.0.bi"
' Repository version 1.2
TYPE AS guint HWND
TYPE AS gulong HICON
TYPE AS gulong HGDIOBJ
EXTERN "C"
' P_X

' P_3

' P_4

END EXTERN

