'            FreeBasic header file, auto-generated by
'                       ### girtobac ###
' LGPLv2.1 (C) 2013-2022 by Thomas{ doT ]Freiherr[ At ]gmx[ DoT }net
' Auto-translated from file /usr/share/gir-1.0/xft-2.0.gir
#INCLUDE ONCE "_GirToBac-0.0.bi"
' Repository version 1.2
#INCLUDE ONCE "xlib-2.0.bi"
TYPE AS _XftColor XftColor
TYPE AS _XftDraw XftDraw
TYPE AS _XftFont XftFont
TYPE AS _XftGlyphSpec XftGlyphSpec
EXTERN "C"
' P_X

' P_3

' P_4

DECLARE SUB XftInit()
END EXTERN

