#INCLUDE Once "SysUtils.bi"
#INCLUDE Once "Graphics.bi"
#INCLUDE Once "Control.bi"
#INCLUDE Once "Graphic.bi"
#INCLUDE Once "Canvas.bi"
#INCLUDE Once "Classes.bi"
#INCLUDE Once "Application.bi"
#INCLUDE Once "Dialogs.bi"
#INCLUDE Once "Form.bi"
'...
