'###############################################################################
' This file is part of MyFBFramework
' Authors: UEZ, Xusinboy Bekchanov, Liu XiaLin
' Based on UEZ's abstract version.
' Direct2D 1.2 API - FreeBASIC Translation
' Adapted by Xusinboy Bekchanov, Liu XiaLin
'###############################################################################
#include "d2d1effects_1.bi"
#pragma once
' ---------------------------------------------------------------------------
' D2D1 Effects 2 (from d2d1effects_2.idl)
' ---------------------------------------------------------------------------
#ifndef __D2D1EFFECTS_2_BI
#define __D2D1EFFECTS_2_BI
' Enumeration für die Highlights- und Shadows-Effekteigenschaften
Type D2D1_HIGHLIGHTSANDSHADOWS_PROP As Long
Enum
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_HIGHLIGHTS       = &h0
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_SHADOWS          = &h1
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_CLARITY          = &h2
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_INPUT_GAMMA      = &h3
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_MASK_BLUR_RADIUS = &h4
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_FORCE_DWORD      = &hFFFFFFFF
End Enum
' Enumeration für den Gamma-Modus (Input Gamma)
Type D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA As Long
Enum
    D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_LINEAR = 0
    D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_SRGB   = 1
    D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_3DTRANSFORM_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_3dtransform_prop
Type D2D1_3DTRANSFORM_PROP As Long
Enum
    D2D1_3DTRANSFORM_PROP_INTERPOLATION_MODE = 0,
    D2D1_3DTRANSFORM_PROP_BORDER_MODE = 1,
    D2D1_3DTRANSFORM_PROP_TRANSFORM_MATRIX = 2
    D2D1_3DTRANSFORM_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_3DTRANSFORM_INTERPOLATION_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_3dtransform_interpolation_mode
Type D2D1_3DTRANSFORM_INTERPOLATION_MODE As Long
Enum
    D2D1_3DTRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_3DTRANSFORM_INTERPOLATION_MODE_LINEAR = 1,
    D2D1_3DTRANSFORM_INTERPOLATION_MODE_CUBIC = 2,
    D2D1_3DTRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_3DTRANSFORM_INTERPOLATION_MODE_ANISOTROPIC = 4
    D2D1_3DTRANSFORM_INTERPOLATION_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DPICOMPENSATION_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_dpicompensation_prop
Type D2D1_DPICOMPENSATION_PROP As Long
Enum
    D2D1_DPICOMPENSATION_PROP_INTERPOLATION_MODE = 0,
    D2D1_DPICOMPENSATION_PROP_BORDER_MODE = 1,
    D2D1_DPICOMPENSATION_PROP_INPUT_DPI = 2
    D2D1_DPICOMPENSATION_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DPICOMPENSATION_INTERPOLATION_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_dpicompensation_interpolation_mode
Type D2D1_DPICOMPENSATION_INTERPOLATION_MODE As Long
Enum
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_LINEAR = 1,
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_CUBIC = 2,
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_ANISOTROPIC = 4,
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_DPICOMPENSATION_INTERPOLATION_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_TURBULENCE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_turbulence_prop
Type D2D1_TURBULENCE_PROP As Long
Enum
    D2D1_TURBULENCE_PROP_OFFSET = 0,
    D2D1_TURBULENCE_PROP_SIZE = 1,
    D2D1_TURBULENCE_PROP_BASE_FREQUENCY = 2,
    D2D1_TURBULENCE_PROP_NUM_OCTAVES = 3,
    D2D1_TURBULENCE_PROP_SEED = 4,
    D2D1_TURBULENCE_PROP_NOISE = 5,
    D2D1_TURBULENCE_PROP_STITCHABLE = 6
    D2D1_TURBULENCE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DISPLACEMENTMAP_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_displacementmap_prop
Type D2D1_DISPLACEMENTMAP_PROP As Long
Enum
    D2D1_DISPLACEMENTMAP_PROP_SCALE = 0,
    D2D1_DISPLACEMENTMAP_PROP_X_CHANNEL_SELECT = 1,
    D2D1_DISPLACEMENTMAP_PROP_Y_CHANNEL_SELECT = 2
    D2D1_DISPLACEMENTMAP_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_COLORMANAGEMENT_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_colormanagement_prop
Type D2D1_COLORMANAGEMENT_PROP As Long
Enum
    D2D1_COLORMANAGEMENT_PROP_SOURCE_COLOR_CONTEXT = 0,
    D2D1_COLORMANAGEMENT_PROP_SOURCE_RENDERING_INTENT = 1,
    D2D1_COLORMANAGEMENT_PROP_DESTINATION_COLOR_CONTEXT = 2,
    D2D1_COLORMANAGEMENT_PROP_DESTINATION_RENDERING_INTENT = 3,
    D2D1_COLORMANAGEMENT_PROP_ALPHA_MODE = 4,
    D2D1_COLORMANAGEMENT_PROP_QUALITY = 5
    D2D1_COLORMANAGEMENT_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_COLORMANAGEMENT_ALPHA_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_colormanagement_alpha_mode
Type D2D1_COLORMANAGEMENT_ALPHA_MODE As Long
Enum
    D2D1_COLORMANAGEMENT_ALPHA_MODE_PREMULTIPLIED = 1,
    D2D1_COLORMANAGEMENT_ALPHA_MODE_STRAIGHT = 2
    D2D1_COLORMANAGEMENT_ALPHA_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_COLORMANAGEMENT_QUALITY documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_colormanagement_quality
Type D2D1_COLORMANAGEMENT_QUALITY As Long
Enum
    D2D1_COLORMANAGEMENT_QUALITY_PROOF = 0,
    D2D1_COLORMANAGEMENT_QUALITY_NORMAL = 1,
    D2D1_COLORMANAGEMENT_QUALITY_BEST = 2
    D2D1_COLORMANAGEMENT_QUALITY_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_COLORMANAGEMENT_RENDERING_INTENT documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_colormanagement_rendering_intent
Type D2D1_COLORMANAGEMENT_RENDERING_INTENT As Long
Enum
    D2D1_COLORMANAGEMENT_RENDERING_INTENT_PERCEPTUAL = 0,
    D2D1_COLORMANAGEMENT_RENDERING_INTENT_RELATIVE_COLORIMETRIC = 1,
    D2D1_COLORMANAGEMENT_RENDERING_INTENT_SATURATION = 2,
    D2D1_COLORMANAGEMENT_RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 3
    D2D1_COLORMANAGEMENT_RENDERING_INTENT_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_HISTOGRAM_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_histogram_prop
Type D2D1_HISTOGRAM_PROP As Long
Enum
    D2D1_HISTOGRAM_PROP_NUM_BINS = 0,
    D2D1_HISTOGRAM_PROP_CHANNEL_SELECT = 1,
    D2D1_HISTOGRAM_PROP_HISTOGRAM_OUTPUT = 2
    D2D1_HISTOGRAM_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_SPOTSPECULAR_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_spotspecular_prop
Type D2D1_SPOTSPECULAR_PROP As Long
Enum
    D2D1_SPOTSPECULAR_PROP_LIGHT_POSITION = 0,
    D2D1_SPOTSPECULAR_PROP_POINTS_AT = 1,
    D2D1_SPOTSPECULAR_PROP_FOCUS = 2,
    D2D1_SPOTSPECULAR_PROP_LIMITING_CONE_ANGLE = 3,
    D2D1_SPOTSPECULAR_PROP_SPECULAR_EXPONENT = 4,
    D2D1_SPOTSPECULAR_PROP_SPECULAR_CONSTANT = 5,
    D2D1_SPOTSPECULAR_PROP_SURFACE_SCALE = 6,
    D2D1_SPOTSPECULAR_PROP_COLOR = 7,
    D2D1_SPOTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 8,
    D2D1_SPOTSPECULAR_PROP_SCALE_MODE = 9
    D2D1_SPOTSPECULAR_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_SPOTSPECULAR_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_spotspecular_scale_mode
Type D2D1_SPOTSPECULAR_SCALE_MODE As Long
Enum
    D2D1_SPOTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_SPOTSPECULAR_SCALE_MODE_LINEAR = 1,
    D2D1_SPOTSPECULAR_SCALE_MODE_CUBIC = 2,
    D2D1_SPOTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_SPOTSPECULAR_SCALE_MODE_ANISOTROPIC = 4,
    D2D1_SPOTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_SPOTSPECULAR_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DISTANTSPECULAR_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_distantspecular_prop
Type D2D1_DISTANTSPECULAR_PROP As Long
Enum
    D2D1_DISTANTSPECULAR_PROP_AZIMUTH = 0,
    D2D1_DISTANTSPECULAR_PROP_ELEVATION = 1,
    D2D1_DISTANTSPECULAR_PROP_SPECULAR_EXPONENT = 2,
    D2D1_DISTANTSPECULAR_PROP_SPECULAR_CONSTANT = 3,
    D2D1_DISTANTSPECULAR_PROP_SURFACE_SCALE = 4,
    D2D1_DISTANTSPECULAR_PROP_COLOR = 5,
    D2D1_DISTANTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 6,
    D2D1_DISTANTSPECULAR_PROP_SCALE_MODE = 7
    D2D1_DISTANTSPECULAR_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DISTANTSPECULAR_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_distantspecular_scale_mode
Type D2D1_DISTANTSPECULAR_SCALE_MODE As Long
Enum
    D2D1_DISTANTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_DISTANTSPECULAR_SCALE_MODE_LINEAR = 1,
    D2D1_DISTANTSPECULAR_SCALE_MODE_CUBIC = 2,
    D2D1_DISTANTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_DISTANTSPECULAR_SCALE_MODE_ANISOTROPIC = 4,
    D2D1_DISTANTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_DISTANTSPECULAR_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_POINTDIFFUSE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_pointdiffuse_prop
Type D2D1_POINTDIFFUSE_PROP As Long
Enum
    D2D1_POINTDIFFUSE_PROP_LIGHT_POSITION = 0,
    D2D1_POINTDIFFUSE_PROP_DIFFUSE_CONSTANT = 1,
    D2D1_POINTDIFFUSE_PROP_SURFACE_SCALE = 2,
    D2D1_POINTDIFFUSE_PROP_COLOR = 3,
    D2D1_POINTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 4,
    D2D1_POINTDIFFUSE_PROP_SCALE_MODE = 5
    D2D1_POINTDIFFUSE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_POINTDIFFUSE_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_pointdiffuse_scale_mode
Type D2D1_POINTDIFFUSE_SCALE_MODE As Long
Enum
    D2D1_POINTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_POINTDIFFUSE_SCALE_MODE_LINEAR = 1,
    D2D1_POINTDIFFUSE_SCALE_MODE_CUBIC = 2,
    D2D1_POINTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_POINTDIFFUSE_SCALE_MODE_ANISOTROPIC = 4,
    D2D1_POINTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_POINTDIFFUSE_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_SPOTDIFFUSE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_spotdiffuse_prop
Type D2D1_SPOTDIFFUSE_PROP As Long
Enum
    D2D1_SPOTDIFFUSE_PROP_LIGHT_POSITION = 0,
    D2D1_SPOTDIFFUSE_PROP_POINTS_AT = 1,
    D2D1_SPOTDIFFUSE_PROP_FOCUS = 2,
    D2D1_SPOTDIFFUSE_PROP_LIMITING_CONE_ANGLE = 3,
    D2D1_SPOTDIFFUSE_PROP_DIFFUSE_CONSTANT = 4,
    D2D1_SPOTDIFFUSE_PROP_SURFACE_SCALE = 5,
    D2D1_SPOTDIFFUSE_PROP_COLOR = 6,
    D2D1_SPOTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 7,
    D2D1_SPOTDIFFUSE_PROP_SCALE_MODE = 8
    D2D1_SPOTDIFFUSE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_SPOTDIFFUSE_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_spotdiffuse_scale_mode
Type D2D1_SPOTDIFFUSE_SCALE_MODE As Long
Enum
    D2D1_SPOTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_SPOTDIFFUSE_SCALE_MODE_LINEAR = 1,
    D2D1_SPOTDIFFUSE_SCALE_MODE_CUBIC = 2,
    D2D1_SPOTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_SPOTDIFFUSE_SCALE_MODE_ANISOTROPIC = 4,
    D2D1_SPOTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_SPOTDIFFUSE_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DISTANTDIFFUSE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_distantdiffuse_prop
Type D2D1_DISTANTDIFFUSE_PROP As Long
Enum
    D2D1_DISTANTDIFFUSE_PROP_AZIMUTH = 0,
    D2D1_DISTANTDIFFUSE_PROP_ELEVATION = 1,
    D2D1_DISTANTDIFFUSE_PROP_DIFFUSE_CONSTANT = 2,
    D2D1_DISTANTDIFFUSE_PROP_SURFACE_SCALE = 3,
    D2D1_DISTANTDIFFUSE_PROP_COLOR = 4,
    D2D1_DISTANTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 5,
    D2D1_DISTANTDIFFUSE_PROP_SCALE_MODE = 6
    D2D1_DISTANTDIFFUSE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DISTANTDIFFUSE_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_distantdiffuse_scale_mode
Type D2D1_DISTANTDIFFUSE_SCALE_MODE As Long
Enum
    D2D1_DISTANTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_DISTANTDIFFUSE_SCALE_MODE_LINEAR = 1,
    D2D1_DISTANTDIFFUSE_SCALE_MODE_CUBIC = 2,
    D2D1_DISTANTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_DISTANTDIFFUSE_SCALE_MODE_ANISOTROPIC = 4,
    D2D1_DISTANTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_DISTANTDIFFUSE_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_LINEARTRANSFER_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_lineartransfer_prop
Type D2D1_LINEARTRANSFER_PROP As Long
Enum
    D2D1_LINEARTRANSFER_PROP_RED_Y_INTERCEPT = 0,
    D2D1_LINEARTRANSFER_PROP_RED_SLOPE = 1,
    D2D1_LINEARTRANSFER_PROP_RED_DISABLE = 2,
    D2D1_LINEARTRANSFER_PROP_GREEN_Y_INTERCEPT = 3,
    D2D1_LINEARTRANSFER_PROP_GREEN_SLOPE = 4,
    D2D1_LINEARTRANSFER_PROP_GREEN_DISABLE = 5,
    D2D1_LINEARTRANSFER_PROP_BLUE_Y_INTERCEPT = 6,
    D2D1_LINEARTRANSFER_PROP_BLUE_SLOPE = 7,
    D2D1_LINEARTRANSFER_PROP_BLUE_DISABLE = 8,
    D2D1_LINEARTRANSFER_PROP_ALPHA_Y_INTERCEPT = 9,
    D2D1_LINEARTRANSFER_PROP_ALPHA_SLOPE = 10,
    D2D1_LINEARTRANSFER_PROP_ALPHA_DISABLE = 11,
    D2D1_LINEARTRANSFER_PROP_CLAMP_OUTPUT = 12
    D2D1_LINEARTRANSFER_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_GAMMATRANSFER_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_gammatransfer_prop
Type D2D1_GAMMATRANSFER_PROP As Long
Enum
    D2D1_GAMMATRANSFER_PROP_RED_AMPLITUDE = 0,
    D2D1_GAMMATRANSFER_PROP_RED_EXPONENT = 1,
    D2D1_GAMMATRANSFER_PROP_RED_OFFSET = 2,
    D2D1_GAMMATRANSFER_PROP_RED_DISABLE = 3,
    D2D1_GAMMATRANSFER_PROP_GREEN_AMPLITUDE = 4,
    D2D1_GAMMATRANSFER_PROP_GREEN_EXPONENT = 5,
    D2D1_GAMMATRANSFER_PROP_GREEN_OFFSET = 6,
    D2D1_GAMMATRANSFER_PROP_GREEN_DISABLE = 7,
    D2D1_GAMMATRANSFER_PROP_BLUE_AMPLITUDE = 8,
    D2D1_GAMMATRANSFER_PROP_BLUE_EXPONENT = 9,
    D2D1_GAMMATRANSFER_PROP_BLUE_OFFSET = 10,
    D2D1_GAMMATRANSFER_PROP_BLUE_DISABLE = 11,
    D2D1_GAMMATRANSFER_PROP_ALPHA_AMPLITUDE = 12,
    D2D1_GAMMATRANSFER_PROP_ALPHA_EXPONENT = 13,
    D2D1_GAMMATRANSFER_PROP_ALPHA_OFFSET = 14,
    D2D1_GAMMATRANSFER_PROP_ALPHA_DISABLE = 15,
    D2D1_GAMMATRANSFER_PROP_CLAMP_OUTPUT = 16
    D2D1_GAMMATRANSFER_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_TABLETRANSFER_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_tabletransfer_prop
Type D2D1_TABLETRANSFER_PROP As Long
Enum
    D2D1_TABLETRANSFER_PROP_RED_TABLE = 0,
    D2D1_TABLETRANSFER_PROP_RED_DISABLE = 1,
    D2D1_TABLETRANSFER_PROP_GREEN_TABLE = 2,
    D2D1_TABLETRANSFER_PROP_GREEN_DISABLE = 3,
    D2D1_TABLETRANSFER_PROP_BLUE_TABLE = 4,
    D2D1_TABLETRANSFER_PROP_BLUE_DISABLE = 5,
    D2D1_TABLETRANSFER_PROP_ALPHA_TABLE = 6,
    D2D1_TABLETRANSFER_PROP_ALPHA_DISABLE = 7,
    D2D1_TABLETRANSFER_PROP_CLAMP_OUTPUT = 8
    D2D1_TABLETRANSFER_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_DISCRETETRANSFER_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_discretetransfer_prop
Type D2D1_DISCRETETRANSFER_PROP As Long
Enum
    D2D1_DISCRETETRANSFER_PROP_RED_TABLE = 0,
    D2D1_DISCRETETRANSFER_PROP_RED_DISABLE = 1,
    D2D1_DISCRETETRANSFER_PROP_GREEN_TABLE = 2,
    D2D1_DISCRETETRANSFER_PROP_GREEN_DISABLE = 3,
    D2D1_DISCRETETRANSFER_PROP_BLUE_TABLE = 4,
    D2D1_DISCRETETRANSFER_PROP_BLUE_DISABLE = 5,
    D2D1_DISCRETETRANSFER_PROP_ALPHA_TABLE = 6,
    D2D1_DISCRETETRANSFER_PROP_ALPHA_DISABLE = 7,
    D2D1_DISCRETETRANSFER_PROP_CLAMP_OUTPUT = 8
    D2D1_DISCRETETRANSFER_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_CONVOLVEMATRIX_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_convolvematrix_prop
Type D2D1_CONVOLVEMATRIX_PROP As Long
Enum
    D2D1_CONVOLVEMATRIX_PROP_KERNEL_UNIT_LENGTH = 0,
    D2D1_CONVOLVEMATRIX_PROP_SCALE_MODE = 1,
    D2D1_CONVOLVEMATRIX_PROP_KERNEL_SIZE_X = 2,
    D2D1_CONVOLVEMATRIX_PROP_KERNEL_SIZE_Y = 3,
    D2D1_CONVOLVEMATRIX_PROP_KERNEL_MATRIX = 4,
    D2D1_CONVOLVEMATRIX_PROP_DIVISOR = 5,
    D2D1_CONVOLVEMATRIX_PROP_BIAS = 6,
    D2D1_CONVOLVEMATRIX_PROP_KERNEL_OFFSET = 7,
    D2D1_CONVOLVEMATRIX_PROP_PRESERVE_ALPHA = 8,
    D2D1_CONVOLVEMATRIX_PROP_BORDER_MODE = 9,
    D2D1_CONVOLVEMATRIX_PROP_CLAMP_OUTPUT = 10
    D2D1_CONVOLVEMATRIX_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_CONVOLVEMATRIX_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_convolvematrix_scale_mode
Type D2D1_CONVOLVEMATRIX_SCALE_MODE As Long
Enum
    D2D1_CONVOLVEMATRIX_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_CONVOLVEMATRIX_SCALE_MODE_LINEAR = 1,
    D2D1_CONVOLVEMATRIX_SCALE_MODE_CUBIC = 2,
    D2D1_CONVOLVEMATRIX_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_CONVOLVEMATRIX_SCALE_MODE_ANISOTROPIC = 4,
    D2D1_CONVOLVEMATRIX_SCALE_MODE_HIGH_QUALITY_CUBIC = 5
    D2D1_CONVOLVEMATRIX_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_BORDER_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_border_prop
Type D2D1_BORDER_PROP As Long
Enum
    D2D1_BORDER_PROP_EDGE_MODE_X = 0,
    D2D1_BORDER_PROP_EDGE_MODE_Y = 1
    D2D1_BORDER_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_BORDER_EDGE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_border_edge_mode
Type D2D1_BORDER_EDGE_MODE As Long
Enum
    D2D1_BORDER_EDGE_MODE_CLAMP = 0,
    D2D1_BORDER_EDGE_MODE_WRAP = 1,
    D2D1_BORDER_EDGE_MODE_MIRROR = 2
    D2D1_BORDER_EDGE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_MORPHOLOGY_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_morphology_prop
Type D2D1_MORPHOLOGY_PROP As Long
Enum
    D2D1_MORPHOLOGY_PROP_MODE = 0,
    D2D1_MORPHOLOGY_PROP_WIDTH = 1,
    D2D1_MORPHOLOGY_PROP_HEIGHT = 2
    D2D1_MORPHOLOGY_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_MORPHOLOGY_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_morphology_mode
Type D2D1_MORPHOLOGY_MODE As Long
Enum
    D2D1_MORPHOLOGY_MODE_ERODE = 0,
    D2D1_MORPHOLOGY_MODE_DILATE = 1
    D2D1_MORPHOLOGY_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_TILE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_tile_prop
Type D2D1_TILE_PROP As Long
Enum
    D2D1_TILE_PROP_RECT = 0
    D2D1_TILE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_ATLAS_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_atlas_prop
Type D2D1_ATLAS_PROP As Long
Enum
    D2D1_ATLAS_PROP_INPUT_RECT = 0,
    D2D1_ATLAS_PROP_INPUT_PADDING_RECT = 1
    D2D1_ATLAS_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_OPACITYMETADATA_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_opacitymetadata_prop
Type D2D1_OPACITYMETADATA_PROP As Long
Enum
    D2D1_OPACITYMETADATA_PROP_INPUT_OPAQUE_RECT = 0
    D2D1_OPACITYMETADATA_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_CHANGE_TYPE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_change_type
Type D2D1_CHANGE_TYPE As Long
Enum
    D2D1_CHANGE_TYPE_NONE = 0,
    D2D1_CHANGE_TYPE_PROPERTIES = 1,
    D2D1_CHANGE_TYPE_CONTEXT = 2,
    D2D1_CHANGE_TYPE_GRAPH = 3
    D2D1_CHANGE_TYPE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_PIXEL_OPTIONS documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_pixel_options
Type D2D1_PIXEL_OPTIONS As Long
Enum
    D2D1_PIXEL_OPTIONS_NONE = 0,
    D2D1_PIXEL_OPTIONS_TRIVIAL_SAMPLING = 1
    D2D1_PIXEL_OPTIONS_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_VERTEX_OPTIONS documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_vertex_options
Type D2D1_VERTEX_OPTIONS As Long
Enum
    D2D1_VERTEX_OPTIONS_NONE = 0,
    D2D1_VERTEX_OPTIONS_DO_NOT_CLEAR = 1,
    D2D1_VERTEX_OPTIONS_USE_DEPTH_BUFFER = 2,
    D2D1_VERTEX_OPTIONS_ASSUME_NO_OVERLAP = 4
    D2D1_VERTEX_OPTIONS_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_VERTEX_USAGE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_vertex_usage
Type D2D1_VERTEX_USAGE As Long
Enum
    D2D1_VERTEX_USAGE_STATIC = 0,
    D2D1_VERTEX_USAGE_DYNAMIC = 1
    D2D1_VERTEX_USAGE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_BLEND_OPERATION documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_blend_operation
Type D2D1_BLEND_OPERATION As Long
Enum
    D2D1_BLEND_OPERATION_ADD = 1,
    D2D1_BLEND_OPERATION_SUBTRACT = 2,
    D2D1_BLEND_OPERATION_REV_SUBTRACT = 3,
    D2D1_BLEND_OPERATION_MIN = 4,
    D2D1_BLEND_OPERATION_MAX = 5
    D2D1_BLEND_OPERATION_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_BLEND documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_blend
Type D2D1_BLEND As Long
Enum
    D2D1_BLEND_ZERO = 1,
    D2D1_BLEND_ONE = 2,
    D2D1_BLEND_SRC_COLOR = 3,
    D2D1_BLEND_INV_SRC_COLOR = 4,
    D2D1_BLEND_SRC_ALPHA = 5,
    D2D1_BLEND_INV_SRC_ALPHA = 6,
    D2D1_BLEND_DEST_ALPHA = 7,
    D2D1_BLEND_INV_DEST_ALPHA = 8,
    D2D1_BLEND_DEST_COLOR = 9,
    D2D1_BLEND_INV_DEST_COLOR = 10,
    D2D1_BLEND_SRC_ALPHA_SAT = 11,
    D2D1_BLEND_BLEND_FACTOR = 14,
    D2D1_BLEND_INV_BLEND_FACTOR = 15
    D2D1_BLEND_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_CHANNEL_DEPTH documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_channel_depth
Type D2D1_CHANNEL_DEPTH As Long
Enum
    D2D1_CHANNEL_DEPTH_DEFAULT = 0,
    D2D1_CHANNEL_DEPTH_1 = 1,
    D2D1_CHANNEL_DEPTH_4 = 4
    D2D1_CHANNEL_DEPTH_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_FILTER documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_filter
Type D2D1_FILTER As Long
Enum
    D2D1_FILTER_MIN_MAG_MIP_POINT = 0,
    D2D1_FILTER_MIN_MAG_POINT_MIP_LINEAR = 1,
    D2D1_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT = 4,
    D2D1_FILTER_MIN_POINT_MAG_MIP_LINEAR = 5,
    D2D1_FILTER_MIN_LINEAR_MAG_MIP_POINT = 16,
    D2D1_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 17,
    D2D1_FILTER_MIN_MAG_LINEAR_MIP_POINT = 20,
    D2D1_FILTER_MIN_MAG_MIP_LINEAR = 21,
    D2D1_FILTER_ANISOTROPIC = 85
    D2D1_FILTER_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_FEATURE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effectauthor/ne-d2d1effectauthor-d2d1_feature
Type D2D1_FEATURE As Long
Enum
    D2D1_FEATURE_DOUBLES = 0,
    D2D1_FEATURE_D3D10_X_HARDWARE_OPTIONS = 1
    D2D1_FEATURE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_CONTRAST_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_contrast_prop
Type D2D1_CONTRAST_PROP As Long
Enum
    D2D1_CONTRAST_PROP_CONTRAST = 0,
    D2D1_CONTRAST_PROP_CLAMP_INPUT = 1
    D2D1_CONTRAST_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_RGBTOHUE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_rgbtohue_prop
Type D2D1_RGBTOHUE_PROP As Long
Enum
    D2D1_RGBTOHUE_PROP_OUTPUT_COLOR_SPACE = 0
    D2D1_RGBTOHUE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_rgbtohue_output_color_space
Type D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE As Long
Enum
    D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE_HUE_SATURATION_VALUE = 0,
    D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE_HUE_SATURATION_LIGHTNESS = 1
    D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_HUETORGB_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_huetorgb_prop
Type D2D1_HUETORGB_PROP As Long
Enum
    D2D1_HUETORGB_PROP_INPUT_COLOR_SPACE = 0
    D2D1_HUETORGB_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_HUETORGB_INPUT_COLOR_SPACE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_huetorgb_input_color_space
Type D2D1_HUETORGB_INPUT_COLOR_SPACE As Long
Enum
    D2D1_HUETORGB_INPUT_COLOR_SPACE_HUE_SATURATION_VALUE = 0,
    D2D1_HUETORGB_INPUT_COLOR_SPACE_HUE_SATURATION_LIGHTNESS = 1
    D2D1_HUETORGB_INPUT_COLOR_SPACE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_CHROMAKEY_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_chromakey_prop
Type D2D1_CHROMAKEY_PROP As Long
Enum
    D2D1_CHROMAKEY_PROP_COLOR = 0,
    D2D1_CHROMAKEY_PROP_TOLERANCE = 1,
    D2D1_CHROMAKEY_PROP_INVERT_ALPHA = 2,
    D2D1_CHROMAKEY_PROP_FEATHER = 3
    D2D1_CHROMAKEY_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_EMBOSS_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_emboss_prop
Type D2D1_EMBOSS_PROP As Long
Enum
    D2D1_EMBOSS_PROP_HEIGHT = 0,
    D2D1_EMBOSS_PROP_DIRECTION = 1
    D2D1_EMBOSS_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_EXPOSURE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_exposure_prop
Type D2D1_EXPOSURE_PROP As Long
Enum
    D2D1_EXPOSURE_PROP_EXPOSURE_VALUE = 0
    D2D1_EXPOSURE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_POSTERIZE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_posterize_prop
Type D2D1_POSTERIZE_PROP As Long
Enum
    D2D1_POSTERIZE_PROP_RED_VALUE_COUNT = 0,
    D2D1_POSTERIZE_PROP_GREEN_VALUE_COUNT = 1,
    D2D1_POSTERIZE_PROP_BLUE_VALUE_COUNT = 2
    D2D1_POSTERIZE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_SEPIA_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_sepia_prop
Type D2D1_SEPIA_PROP As Long
Enum
    D2D1_SEPIA_PROP_INTENSITY = 0,
    D2D1_SEPIA_PROP_ALPHA_MODE = 1
    D2D1_SEPIA_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_SHARPEN_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_sharpen_prop
Type D2D1_SHARPEN_PROP As Long
Enum
    D2D1_SHARPEN_PROP_SHARPNESS = 0,
    D2D1_SHARPEN_PROP_THRESHOLD = 1
    D2D1_SHARPEN_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_STRAIGHTEN_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_straighten_prop
Type D2D1_STRAIGHTEN_PROP As Long
Enum
    D2D1_STRAIGHTEN_PROP_ANGLE = 0,
    D2D1_STRAIGHTEN_PROP_MAINTAIN_SIZE = 1,
    D2D1_STRAIGHTEN_PROP_SCALE_MODE = 2
    D2D1_STRAIGHTEN_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_STRAIGHTEN_SCALE_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_straighten_scale_mode
Type D2D1_STRAIGHTEN_SCALE_MODE As Long
Enum
    D2D1_STRAIGHTEN_SCALE_MODE_NEAREST_NEIGHBOR = 0,
    D2D1_STRAIGHTEN_SCALE_MODE_LINEAR = 1,
    D2D1_STRAIGHTEN_SCALE_MODE_CUBIC = 2,
    D2D1_STRAIGHTEN_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
    D2D1_STRAIGHTEN_SCALE_MODE_ANISOTROPIC = 4
    D2D1_STRAIGHTEN_SCALE_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_TEMPERATUREANDTINT_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_temperatureandtint_prop
Type D2D1_TEMPERATUREANDTINT_PROP As Long
Enum
    D2D1_TEMPERATUREANDTINT_PROP_TEMPERATURE = 0,
    D2D1_TEMPERATUREANDTINT_PROP_TINT = 1
    D2D1_TEMPERATUREANDTINT_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_VIGNETTE_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_vignette_prop
Type D2D1_VIGNETTE_PROP As Long
Enum
    D2D1_VIGNETTE_PROP_COLOR = 0,
    D2D1_VIGNETTE_PROP_TRANSITION_SIZE = 1,
    D2D1_VIGNETTE_PROP_STRENGTH = 2
    D2D1_VIGNETTE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_EDGEDETECTION_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_edgedetection_prop
Type D2D1_EDGEDETECTION_PROP As Long
Enum
    D2D1_EDGEDETECTION_PROP_STRENGTH = 0,
    D2D1_EDGEDETECTION_PROP_BLUR_RADIUS = 1,
    D2D1_EDGEDETECTION_PROP_MODE = 2,
    D2D1_EDGEDETECTION_PROP_OVERLAY_EDGES = 3,
    D2D1_EDGEDETECTION_PROP_ALPHA_MODE = 4
    D2D1_EDGEDETECTION_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_EDGEDETECTION_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_edgedetection_mode
Type D2D1_EDGEDETECTION_MODE As Long
Enum
    D2D1_EDGEDETECTION_MODE_SOBEL = 0,
    D2D1_EDGEDETECTION_MODE_PREWITT = 1
    D2D1_EDGEDETECTION_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_LOOKUPTABLE3D_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_lookuptable3d_prop
Type D2D1_LOOKUPTABLE3D_PROP As Long
Enum
    D2D1_LOOKUPTABLE3D_PROP_LUT = 0,
    D2D1_LOOKUPTABLE3D_PROP_ALPHA_MODE = 1
    D2D1_LOOKUPTABLE3D_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
Type D2D1_OPACITY_PROP As Long
Enum
    D2D1_OPACITY_PROP_OPACITY = 0
    D2D1_OPACITY_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
Type D2D1_CROSSFADE_PROP As Long
Enum
    D2D1_CROSSFADE_PROP_WEIGHT = 0
    D2D1_CROSSFADE_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
Type D2D1_TINT_PROP As Long
Enum
    D2D1_TINT_PROP_COLOR = 0,
    D2D1_TINT_PROP_CLAMP_OUTPUT = 1
    D2D1_TINT_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_WHITELEVELADJUSTMENT_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_whiteleveladjustment_prop
Type D2D1_WHITELEVELADJUSTMENT_PROP As Long
Enum
    D2D1_WHITELEVELADJUSTMENT_PROP_INPUT_WHITE_LEVEL = 0,
    D2D1_WHITELEVELADJUSTMENT_PROP_OUTPUT_WHITE_LEVEL = 1
    D2D1_WHITELEVELADJUSTMENT_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_HDRTONEMAP_PROP documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_hdrtonemap_prop
Type D2D1_HDRTONEMAP_PROP As Long
Enum
    D2D1_HDRTONEMAP_PROP_INPUT_MAX_LUMINANCE = 0,
    D2D1_HDRTONEMAP_PROP_OUTPUT_MAX_LUMINANCE = 1,
    D2D1_HDRTONEMAP_PROP_DISPLAY_MODE = 2
    D2D1_HDRTONEMAP_PROP_FORCE_DWORD = &hFFFFFFFF
End Enum
' D2D1_HDRTONEMAP_DISPLAY_MODE documentation at https://learn.microsoft.com/windows/win32/api/d2d1effects_2/ne-d2d1effects_2-d2d1_hdrtonemap_display_mode
Type D2D1_HDRTONEMAP_DISPLAY_MODE As Long
Enum
    D2D1_HDRTONEMAP_DISPLAY_MODE_SDR = 0,
    D2D1_HDRTONEMAP_DISPLAY_MODE_HDR = 1
    D2D1_HDRTONEMAP_DISPLAY_MODE_FORCE_DWORD = &hFFFFFFFF
End Enum
#endif ' __D2D1EFFECTS_2_BI
