name: Sync

on:
  push:
    branches: [main]

jobs:
  sync-2-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ github-gitee-LX }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com/hustbeef/MyFbFramework.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com/avata/MyFbFramework.git
          force_update: true  # 强制覆盖目标仓库  
          static_list: ""
